baseURL = "https://laibagillani.pages.dev"
title = "Laiba Galani"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "Laiba Galani"
  description = "CS Student"
  avatarURL = "/main/avatar.jpg"
  AvatarAltText = "avatar"
  avatarSize = "size-s"
  ShowBackToTopButton = true # true or false for "back to top" button on posts

  socialIcons = [
    {name = "twitter", url = "https://example.com"},
    {name = "linkedin", url = "https://example.com"},
    {name = "stackoverflow", url = "https://example.com"},
    {name = "dribbble", url = "https://example.com"},
    {name = "instagram", url = "https://example.com"},
    {name = "twitch", url = "https://example.com"},
    {name = "email", url = "mailto:example@example.com"}
  ]
  metaKeywords = ["blog", "gokarna", "hugo"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/526avijitgupta/gokarna"
    weight = 5

  [[menu.main]]
    identifier = "buymeacoffee"
    pre = "<span data-feather='coffee'></span>"
    url = "https://www.buymeacoffee.com/avijitgupta"
    weight = 6

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 7

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
